[package]
name = "libirctl"
description = "ir-ctl as a library for encoding testing"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL"

[build-dependencies]
cc = "1.0"

[dependencies]
libc = "0.2"
