[package]
name = "generate_test_data"
version = "0.1.0"
authors = ["Sean Young <sean@mess.org>"]
edition = "2021"

[dependencies]
irp = { path = ".." }
regex = "1"
serde_derive = { version = "1.0" }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
rand = "0.8"
peg = "0.8"