[package]
name = "generate_lircd_test_data"
version = "0.1.0"
edition = "2021"

[dependencies]
cir = { path = ".." }
serde_derive = { version = "1.0" }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
nix = "0.25"
rlimit = "0.8"
