[package]
name = "transmogrifier_compare"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
irp = { path = "../irp" }
irptransmogrifier = { workspace = true }
rand = "0.8"
itertools = "0.12"
